---
- name: create api-configmap
  k8s:
    state: present
    definition: "{{ lookup('template', 'nginx-config.yaml.j2') }}"
    namespace: "{{ ns_name }}"

- name: create nginx-pod
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment-nginx.yaml.j2') }}"
    namespace: "{{ ns_name }}"

- name: create nginx-svc
  k8s:
    state: present
    definition: "{{ lookup('template', 'svc-nginx.yaml.j2') }}"
    namespace: "{{ ns_name }}"
