version: '3.7'

services:
  nginx-proxy:
    hostname: nginx
    image: nginx:1.17 #-alpine
    ports:
      - 80:80
    container_name: nginx_proxy
    networks:
      - default
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
  auth.api:
    hostname: auth.api
    image: registry.gitlab.com/dashdevs/pfm/auth
    container_name: auth.api
    ports:
      - 8080:80
    networks:
      - default
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PFM_SERVICE_NAME=auth
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://10.1.1.123:12201"
        tag: "Auth.api"
  obpexporter.service:
    hostname: obpexporter.service
    image: registry.gitlab.com/dashdevs/pfm/obpexporter.service
    container_name: obpexporter.service
    ports:
      - 8081:80
    networks:
      - default
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PFM_SERVICE_NAME=obpexporter
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://10.1.1.123:12201"
        tag: "Obpexporter.service"    
  obp.api:
     hostname: obp.api
     image: registry.gitlab.com/dashdevs/pfm/obpmock.api
     container_name: obp.api
     ports:
       - 8082:80
     networks:
       - default
     environment:
       - ASPNETCORE_URLS=http://+:80
       - ASPNETCORE_ENVIRONMENT=Development
       - PFM_SERVICE_NAME=obp
     logging:
       driver: gelf
       options:
         gelf-address: "tcp://10.1.1.123:12201"
         tag: "Obp.api"    
  transactions.api:
     hostname: transactions.api
     image: registry.gitlab.com/dashdevs/pfm/transactions
     container_name: transactions.api
     ports:
       - 8083:80
     networks:
       - default
     environment:
       - ASPNETCORE_URLS=http://+:80
       - ASPNETCORE_ENVIRONMENT=Development
       - PFM_SERVICE_NAME=transactions
     logging:
       driver: gelf
       options:
         gelf-address: "tcp://10.1.1.123:12201"
         tag: "Transactions.api"
  connections.api:
     hostname: connections.api
     image: registry.gitlab.com/dashdevs/pfm/connections.api
     container_name: connections.api
     ports:
       - 8084:80
     networks:
       - default
     environment:
       - ASPNETCORE_URLS=http://+:80
       - ASPNETCORE_ENVIRONMENT=Development
       - PFM_SERVICE_NAME=connections
     logging:
       driver: gelf
       options:
         gelf-address: "tcp://10.1.1.123:12201"
         tag: "Connections.api" 
  notifications.api:
     hostname: notifications.api
     image: registry.gitlab.com/dashdevs/pfm/notifications/notifications.api
     container_name: notifications.api
     ports:
       - 8085:80
     networks:
       - default
     environment:
       - ASPNETCORE_URLS=http://+:80
       - ASPNETCORE_ENVIRONMENT=Development
       - PFM_SERVICE_NAME=notifications
     logging:
       driver: gelf
       options:
         gelf-address: "tcp://10.1.1.123:12201"
         tag: "Notifications.api"
  notifications.service:
     hostname: notifications.service
     image: registry.gitlab.com/dashdevs/pfm/notifications/notifications.service
     container_name: notifications.service
     ports:
       - 8086:80
     networks:
       - default
     environment:
       - ASPNETCORE_URLS=http://+:80
       - ASPNETCORE_ENVIRONMENT=Development
       - PFM_SERVICE_NAME=notificationsservice
     logging:
       driver: gelf
       options:
         gelf-address: "tcp://10.1.1.123:12201"
         tag: "Notifications.service"
networks:
  default:

          #volumes:
          #  nginx.conf:
 

