---
- name: create obpm-pod
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment-obpm.yaml.j2') }}"
    namespace: "{{ ns_name }}"
##    src: redis-deploy.yaml 
###    namespace: "{{ ns_name }}"
##  register: show_ns_k

- name: create obpm-svc
  k8s:
    state: present
    definition: "{{ lookup('template', 'svc-obpm.yaml.j2') }}"
    namespace: "{{ ns_name }}"
  register: show_ns_k
