---
- name: create obp-exporter-pod
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment-obp-exporter.yaml.j2') }}"
    namespace: "{{ ns_name }}"
##    src: redis-deploy.yaml 
###    namespace: "{{ ns_name }}"
##  register: show_ns_k

- name: create obp-exporter-svc
  k8s:
    state: present
    definition: "{{ lookup('template', 'svc-obp-exporter.yaml.j2') }}"
    namespace: "{{ ns_name }}"
  register: show_ns_k
